# Generated by Django 4.2.25 on 2026-01-19 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_ganados', to='torneos.equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='ronda',
            field=models.CharField(choices=[('cuartos', 'Cuartos de final'), ('semifinales', 'Semifinales'), ('final', 'Final'), ('terminado', 'Terminado')], default='cuartos', max_length=20),
        ),
        migrations.AddField(
            model_name='partido',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torneo',
            name='campeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneos_ganados', to='torneos.equipo'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='estado',
            field=models.CharField(choices=[('planificacion', 'En planificación'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado')], default='planificacion', max_length=20),
        ),
        migrations.AddField(
            model_name='torneo',
            name='llave_generada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torneo',
            name='num_equipos',
            field=models.IntegerField(choices=[(4, '4 equipos'), (8, '8 equipos'), (16, '16 equipos')], default=8),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
