# Generated by Django 4.2.25 on 2026-01-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_partido_ganador_partido_ronda_partido_terminado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
