# Generated by Django 4.2.25 on 2026-01-19 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0003_alter_partido_fecha_alter_partido_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='equipo_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='torneos.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='torneos.equipo'),
        ),
    ]
